### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by msalek** [maartendamen/py-openzwave#9]
hi,

Cython version 0.17.2
python setup.py build

Return :

openzwave.cpp:7181: warning: comparison between signed and unsigned integer expressions
In file included from /usr/include/c++/4.4/utility:63,
                 from openzwave.cpp:254:
openzwave/cpp/src/value_classes/ValueID.h: In constructor âstd::pair<_T1, _T2>::pair() [with _T1 = long long unsigned int, _T2 = OpenZWave::ValueID]â:
openzwave.cpp:1755:   instantiated from here
openzwave/cpp/src/value_classes/ValueID.h:243: error: âOpenZWave::ValueID::ValueID()â is private
/usr/include/c++/4.4/bits/stl_pair.h:80: error: within this context
error: command 'gcc' failed with exit status 1

**Comment by msalek** [comment]
Cython version 0.14.1

cc1plus: warning: command line option â-Wstrict-prototypesâ is valid for C/ObjC but not for C++ [enabled by default]
openzwave.cpp: In function âvoid __pyx_f_9openzwave_callback(const OpenZWave::Notification_, void_)â:
openzwave.cpp:2091:51: error: âType_Errorâ is not a member of âOpenZWave::Notificationâ
openzwave.cpp:2101:54: error: âclass OpenZWave::Notificationâ has no member named âGetErrorCodeâ
openzwave.cpp: In function âPyObject\* __pyx_pf_9openzwave_9PyManager_23getNodeNeighbors(PyObject_, PyObject_, PyObject_)â:
openzwave.cpp:3825:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
openzwave.cpp: In function âPyObject_ __pyx_pf_9openzwave_9PyManager_48getAssociations(PyObject_, PyObject_, PyObject*)â:
openzwave.cpp:6391:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
error: command 'gcc' failed with exit status 1

Any Idea ,?

**Comment by maartendamen** [comment]
What revision of openzwave are you compiling against?

**Comment by msalek** [comment]
latest version from http://code.google.com/p/open-zwave/source/checkout
R586

**Comment by maartendamen** [comment]
Ok, I will check it out..

**Comment by maartendamen** [comment]
Please compile using Cython 0.16 instead of 0.17.. not sure what Cython changed but it works with 0.16 and not with 0.17.

**Comment by Tegereo** [comment]
I can confirm this is still an issue with Cython 0.19. Installing Cython 0.16 did not fix the issue. This is against openzwave r661.

Pyhton packages: 

``` bash
$ pip freeze
Cython==0.16
Mako==0.8.0
MarkupSafe==0.15
Twisted==13.0.0
TxScheduling==1.1
argparse==1.2.1
pyzmq==13.1.0
txZMQ==0.6.2
wsgiref==0.1.2
zope.interface==4.0.5
```

Error Output

``` bash
$ python setup.py build
running build
running build_ext
skipping 'openzwave.cpp' Cython extension (up-to-date)
building 'openzwave' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iopenzwave/cpp/src -Iopenzwave/cpp/src/value_classes -Iopenzwave/cpp/src/platform -I/usr/include/python2.7 -c openzwave.cpp -o build/temp.linux-x86_64-2.7/openzwave.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from openzwave/cpp/src/Notification.h:32:0,
                 from openzwave.cpp:310:
/usr/include/c++/4.7/bits/stl_pair.h: In instantiation of ‘std::pair<_T1, _T2>::pair() [with _T1 = long unsigned int; _T2 = OpenZWave::ValueID]’:
openzwave.cpp:1880:42:   required from here
openzwave/cpp/src/value_classes/ValueID.h:244:3: error: ‘OpenZWave::ValueID::ValueID()’ is private
In file included from /usr/include/c++/4.7/utility:72:0,
                 from openzwave.cpp:300:
/usr/include/c++/4.7/bits/stl_pair.h:101:25: error: within this context
error: command 'gcc' failed with exit status 1
```

**Comment by Tegereo** [comment]
Some more info from upstream openzwave. https://code.google.com/p/open-zwave/issues/detail?id=26

The "fix" listed here worked for me. https://groups.google.com/forum/#!msg/openzwave/GbCnNAo82FU/D4nUBWm4rXUJ

Not sure what ValueID is used for, or if it's a bug upstream that it's now private or not.
